SRCS=GUIDialogAxisDetection.cpp \
     GUIDialogButtonCapture.cpp \
     GUIDialogIgnoreInput.cpp \

LIB=controllerdialogs.a

include ../../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
